#!/bin/bash
#------------------------------------------------------------------------------
#
# kc1mjp-tools package postinst script
#
#------------------------------------------------------------------------------
#--- Main Code
#------------------------------------------------------------------------------

baseDirectory=/opt/kc1mjp-tools
binDirectory=${baseDirectory}/bin

chown -R root:root ${baseDirectory}

for directory in $( find ${baseDirectory} -type d )
do
   chmod 0755 ${directory}
done

for file in $( find ${baseDirectory} -type f )
do
   if [[ $( dirname ${file} ) == "${binDirectory}" ]]
   then
      chmod 0755 ${file}
   else
      chmod 0644 ${file}
   fi
done

exit 0

#------------------------------------------------------------------------------
#--- End Script
#------------------------------------------------------------------------------
